baseURL = "https://Ceici92.github.io/CeciliasBlog"
languageCode = "en-us"
title = "Cecilia's Blog"
theme = "ananke"
publishDir = "docs"
canonifyURLs = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "https://github.com/Ceici92/HugoBlog/blob/master/docs/images/orlova-maria.jpg?raw=true"
  featured_image = "https://github.com/Ceici92/HugoBlog/blob/master/docs/images/jeshoots.jpg?raw=true"
  recent_posts_number = 3
  body_classes = "avenir bg-light-yellow"
  background_color_class = "bg-dark-gray"