baseURL = "https://Ceici92.github.io/HugoBlog"
languageCode = "en-us"
title = "Cecilia's Blog"
theme = "ananke"
publishDir = "docs"
canonifyURLs = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    # background_color_class = "bg-black"
  background_color_class = "https://github.com/Ceici92/HugoBlog/blob/master/docs/images/orlova-maria.jpg?raw=true"
  featured_image = "https://user-images.githubusercontent.com/71452847/95070173-029e6580-0708-11eb-9201-03c8436ec97c.jpg"
  recent_posts_number = 2